services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  service:
    build: services/
    container_name: service
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/root/logs
    environment:
      - TZ=Asia/Kolkata
