openapi: 3.0.0
info:
  contact: {}
  description: Module to manage tasks
  title: Tasks Services
  version: "1.0"
paths:
  /public/tasks:
    get:
      description: Get all the tasks
      operationId: get-task
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/orm.Tasks"
                type: array
      security:
        - http_bearer: []
      summary: Get All Task
      tags:
        - Tasks
  /tasks:
    post:
      description: Create a new task
      operationId: create-task
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.CreateTask"
        description: Task data
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orm.Tasks"
      security:
        - http_bearer: []
      summary: Create
      tags:
        - Tasks
  "/tasks/{id}":
    delete:
      description: Delete task by id
      operationId: delete-task
      parameters:
        - description: Id of the task
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/models.MsgResponse"
      summary: Delete task
      tags:
        - Tasks
    get:
      description: Get a specific task by id
      operationId: get-task-id
      parameters:
        - description: Id of the task
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orm.Tasks"
      summary: Get Task
      tags:
        - Tasks
    put:
      description: update existing task
      operationId: update-task
      parameters:
        - description: Id of the task
          in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/models.UpdateTask"
        description: Task data
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orm.Tasks"
      security:
        - http_bearer: []
      summary: Update Task
      tags:
        - Tasks
tags:
  - description: Tasks services
    name: Tasks
servers:
  - url: http://localhost:8000
components:
  securitySchemes:
    http_bearer:
      in: header
      name: Authorization
      type: apiKey
  schemas:
    models.CreateTask:
      properties:
        description:
          type: string
        title:
          type: string
      type: object
    models.MsgResponse:
      properties:
        msg:
          type: string
      type: object
    models.UpdateTask:
      properties:
        description:
          type: string
        status:
          type: string
        title:
          type: string
      type: object
    orm.Tasks:
      properties:
        createdAt:
          type: string
        description:
          type: string
        id:
          type: integer
        status:
          type: string
        title:
          type: string
        updatedAt:
          type: string
      type: object
