basePath: /
definitions:
  models.CreateTask:
    properties:
      description:
        type: string
      title:
        type: string
    type: object
  models.MsgResponse:
    properties:
      msg:
        type: string
    type: object
  models.UpdateTask:
    properties:
      description:
        type: string
      status:
        type: string
      title:
        type: string
    type: object
  orm.Tasks:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Module to manage tasks
  title: Tasks Services
  version: "1.0"
paths:
  /public/tasks:
    get:
      consumes:
      - application/json
      description: Get all the tasks
      operationId: get-task
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/orm.Tasks'
            type: array
      security:
      - http_bearer: []
      summary: Get All Task
      tags:
      - Tasks
  /tasks:
    post:
      consumes:
      - application/json
      description: Create a new task
      operationId: create-task
      parameters:
      - description: Task data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateTask'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/orm.Tasks'
      security:
      - http_bearer: []
      summary: Create
      tags:
      - Tasks
  /tasks/{id}:
    delete:
      consumes:
      - application/json
      description: Delete task by id
      operationId: delete-task
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.MsgResponse'
      summary: Delete task
      tags:
      - Tasks
    get:
      consumes:
      - application/json
      description: Get a specific task by id
      operationId: get-task-id
      parameters:
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/orm.Tasks'
      summary: Get Task
      tags:
      - Tasks
    put:
      consumes:
      - application/json
      description: update existing task
      operationId: update-task
      parameters:
      - description: Task data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdateTask'
      - description: Id of the task
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/orm.Tasks'
      security:
      - http_bearer: []
      summary: Update Task
      tags:
      - Tasks
schemes:
- http
securityDefinitions:
  http_bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Tasks services
  name: Tasks
