env: local
http:
  writeTimeout: 15
  readTimeout: 15

credentials:
  username: ampl
  password: ampl

private-key-path: keys/private.pem
public-key-path: keys/public.pem

log:
  dir: logs
  file: tasks.log
  level: INFO

db:
  host: postgres
  port: 5432
  user: root
  password: root
  database: TASKS
  maxIdle: 5
  maxOpen: 10
  driver: postgres
  endPoint: NXTOPTION-DB

redis:
  host: redis
  port: 6379
  password:
  database: 0
  dialTimeout: 2000
  readTimeout: 1000
  writeTimeout: 1000
  poolSize: 10